name: CI - Build and push

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    strategy:
      fail-fast: false
      matrix:
        php_version:
          - 8.3
          - 8.2
          - 8.1
          - 8.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.php_version }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/php-fpm:${{ matrix.php_version }}
